#!/bin/bash

message="$@"
channel=`echo $message | awk '{ print $1 }'`
message2=`echo $message | cut -d\  -f2-|sed \
-e 's/ /%20/g' \
-e 's/"//g' \
-e 's/\[/%5B/g' \
-e 's/\]/%5D/g' \
-e 's/{/%7B/g' \
-e 's/}/%7D/g' \
-e 's/|/%7C/g' \
-e 's/&/%26/g' \
-e 's/$/%24/g' \
-e 's/#/%23/g' \
`

/usr/bin/curl -s "https://slack.com/api/chat.postMessage?token=my_aweseme_secure_token&channel=%23$channel&text=$message2&username=Thergioni"

